### ISSUE TITLE
[Bug]: excessive firmware update checks

### ISSUE THREAD

**Issue by vitorsemeano** [travisghansen/hass-opnsense#315]
### What happened?

When the coordinator fetches info from opnsense, it triggers a full update check, making requests to internet in the defined interval time.

For example, if you have the scan interval conf for 30 seconds, it will make update checks every 30 seconds, triggering the internet check in opnsense.

The same happens for the device tracking check, when shouldn't imo. 

### hass-opnsense Version

0.3.9

### OPNsense Firmware

24.7.8

### Home Assistant Version

2024.11.1

### Additional Details

I suggest you revert the endpoint used, to fetch the current firmware status. Based on that, trigger the full update on a dedicated time interval, bigger than the scan interval (using the last time update check was made). 

I believe checking for updates every minute is a waste of requests and resources, so applying this approach would optimize this feature.

**Comment by vitorsemeano** [comment]
> So checking `/api/core/firmware/info` is triggering a check for updates but `/api/core/firmware/status` doesn't trigger an update?

Not sure about that, but would seem so.  I am sure the `/api/core/firmware/info` endpoint is triggering a check each time is called.

**Comment by alexdelprete** [comment]
> I am sure the `/api/core/firmware/info` endpoint is triggering a check each time is called.

can you tell me how to verify this? I'm testing the endpoint and I see nothing in the log suggesting it's triggering the update.

**Comment by vitorsemeano** [comment]
On my DNS server, I notice requests being made for the DNS records associated with the upstream sites to check updates (at least the ones I configured in my instance). These requests match on the time intervals configured to fetch data from opnsense to home assistant.

If I change the time interval in home assistant, these requests made to DNS records matches the new interval. If I stop the opnsense device, those requests sease to exist.

I am assuming these DNS requests that come from opnsense, are actually associated with update checks triggered by calling the opnsense.

I don't have anything else using the opnsense API other than this add-on.

**Comment by alexdelprete** [comment]
I'm not quite convinced that is the case, I'm still trying to find some evidence.

If I check the code here for the /info endpoint, I don't see any firmware update call: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php#L795

While the code for the /status endpoint, I see some firmware probing code: https://github.com/opnsense/core/blob/stable/24.7/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php#L96

**Comment by vitorsemeano** [comment]
> If I check the code here for the /info endpoint, I don't see any firmware update call: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php#L795

If you look at line 832, you will see its calling the actions "firmware remote" and "firmware local". For each of these actions, it will fetch available remote and local updates. For the remote, it will fetch those by making requests to the internet.

Following actions logic, should be firmware action by the name "remote":

https://github.com/opnsense/core/blob/4c2619dead6793c15afecfc9dd8b24a5e365c085/src/opnsense/service/conf/actions.d/actions_firmware.conf#L189

This will call the script launcher.sh that will call the script query.sh. In here, for the type remote, will make the calls:

https://github.com/opnsense/core/blob/4c2619dead6793c15afecfc9dd8b24a5e365c085/src/opnsense/scripts/firmware/query.sh#L57

You can also see that it specifically calls the pkg update of the os. It also seems the action tiers can make the call here, but not entirely sure on that.

> While in the code for the /status endpoint, I see some firmware probing code: https://github.com/opnsense/core/blob/stable/24.7/src/opnsense/mvc/app/controllers/OPNsense/Core/Api/FirmwareController.php#L96

I concur, this is also making requests to the internet.

My suggestion is making this a separate call from the existing probes of the integration. Should have it's own time interval to check for updates.

**Comment by Snuffy2** [comment]
Looking at the code links you both posted, `/api/core/firmware/status` isn't actually triggering a check if it is queried using GET. It does trigger a check if is queried as a POST. This also correlates with the time to complete the query. GET takes about 0.5 seconds and POST takes about 10 seconds. Running it as a POST also updates the `Checked On` time in the UI under System, Firmware, Status. The time does not update when calling as GET.

```
        if ($this->request->isPost()) {
            /* run a synchronous check prior to the result fetch */
            $backend->configdRun('firmware probe');
        }
```

For `/api/core/firmware/info`, I agree that it does appear to be triggering some type of firmware check. However, it doesn't update the `Checked On` time in the UI under System, Firmware, Status. It takes about 10 seconds to run, also indicating it may be doing some type of remote querying. While much more convoluted, I also agree that the code for `info` appears to be performing a remote check.

**Comment by alexdelprete** [comment]
> If you look at line 832, you will see its calling the actions "firmware remote" and "firmware local". For each of these actions, it will fetch available remote and local updates. For the remote, it will fetch those by making requests to the internet.

I'm not sure, I don't see calls to external fetching, it looks like it's parsing, not fetching. Maybe it fetches the repo list to get versions and then parses them, but it doesn't actually update anything. It takes 10s because it has to get/parse versions of ALL addons from configured repos.

> `/api/core/firmware/status` isn't actually triggering a check if it is queried using GET

if that's the case, I think the GET of the /status endpoint is the way to go for our purpose to get OPNsense version.

They could've made it simpler. :)

**Comment by alexdelprete** [comment]
A quick test with postman:

GET /core/firmware/status takes 120ms here while POST takes 5-6s.

The output:

```json
{
    "api_version": "2",
    "connection": "ok",
    "downgrade_packages": [],
    "download_size": "",
    "last_check": "Wed Nov 20 03:21:53 CET 2024",
    "needs_reboot": "0",
    "new_packages": [],
    "os_version": "FreeBSD 14.1-RELEASE-p6",
    "product_id": "opnsense",
    "product_target": "opnsense",
    "product_version": "24.7.8",
    "product_abi": "24.7",
    "reinstall_packages": [],
    "remove_packages": [],
    "repository": "ok",
    "upgrade_major_message": "",
    "upgrade_major_version": "",
    "upgrade_needs_reboot": "0",
    "upgrade_packages": [],
    "upgrade_sets": [],
    "product": {
        "product_abi": "24.7",
        "product_arch": "amd64",
        "product_check": {
            "api_version": "2",
            "connection": "ok",
            "downgrade_packages": [],
            "download_size": "",
            "last_check": "Wed Nov 20 03:21:53 CET 2024",
            "needs_reboot": "0",
            "new_packages": [],
            "os_version": "FreeBSD 14.1-RELEASE-p6",
            "product_id": "opnsense",
            "product_target": "opnsense",
            "product_version": "24.7.8",
            "product_abi": "24.7",
            "reinstall_packages": [],
            "remove_packages": [],
            "repository": "ok",
            "upgrade_major_message": "",
            "upgrade_major_version": "",
            "upgrade_needs_reboot": "0",
            "upgrade_packages": [],
            "upgrade_sets": []
        },
        "product_conflicts": "os-firewall os-firewall-devel os-wireguard os-wireguard-devel os-wireguard-go os-wireguard-go-devel",
        "product_copyright_owner": "Deciso B.V.",
        "product_copyright_url": "https://www.deciso.com/",
        "product_copyright_years": "2014-2024",
        "product_email": "project@opnsense.org",
        "product_hash": "9a689f238",
        "product_id": "opnsense",
        "product_latest": "24.7.8",
        "product_license": [],
        "product_log": 0,
        "product_mirror": "https://pkg.opnsense.org/FreeBSD:14:amd64/24.7",
        "product_name": "OPNsense",
        "product_nickname": "Thriving Tiger",
        "product_repos": "OPNsense (Priority: 11), mimugmail (Priority: 5)",
        "product_series": "24.7",
        "product_tier": "1",
        "product_time": "Wed Nov 6 20:50:44 CET 2024",
        "product_version": "24.7.8",
        "product_website": "https://opnsense.org/"
    },
    "all_packages": [],
    "all_sets": [],
    "status_msg": "There are no updates available on the selected mirror.",
    "status": "none"
}
```

So, if we have that output in a data variable, this gives us OPNsense version:

```python
data.get("product", {}).get("product_version")
```

And it's quick enough to keep the check in the default coordinator polling period.

**Comment by vitorsemeano** [comment]
Changing the endpoint from info to status should fix the problem.

I don't know if opnsense cheks regularly for updates automatically. If it doesn't, is calling the status endpoint with POST from time to time, but not so regularly as the scan interval.

**Comment by SiLenCe-WB** [comment]
Is this issue related to the multiple DNS queries to these two addresses every 30 seconds?

- opn-repo.routerperformance.net
- pkg.opnsense.org 

Is there a solution for it? I would like to keep my sensors at 30 seconds but those queries are generating so much noise on my DNS server.

**Comment by engels0n** [comment]
Bug is back with 2026.4.1 :/ 

<img width="627" height="1002" alt="Image" src="https://github.com/user-attachments/assets/1b8ae49e-4e3b-406c-9b4c-9eade6260f4a" />
