### ISSUE TITLE
[Bug]: KeyError: 'v0.3.10' user_input[CONF_FIRMWARE_VERSION]

### ISSUE THREAD

**Issue by OdinVex** [travisghansen/hass-opnsense#330]
### What happened?

"Connect to the OPNsense firewall / router"

### hass-opnsense Version

0.3.10

### OPNsense Firmware

24.7.9_1

### Home Assistant Version

13.2

### Relevant logs

```shell
File "/config/custom_components/opnsense/config_flow.py", line 234, in async_step_user
    firmware = user_input[CONF_FIRMWARE_VERSION]
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'v0.3.10'
```

**Comment by alexdelprete** [comment]
When does this happen: first configuration, reconfiguration? Please provide some more info on the context.

Are you using a root user?

**Comment by alexdelprete** [comment]
Do you have any error in HA logs?

**Comment by alexdelprete** [comment]
Let's wait for @Snuffy2 to check it.

**Comment by Snuffy2** [comment]
Should be fixed in v0.3.11

**Comment by alexdelprete** [comment]
> but it shouldn't show an unknown error like that if authentication fails (401 should be acknowledged).

401 is acknowledged in the code. maybe there's some other issue...

So the issue of the OP is solved or not? It's not clear. :)

**Comment by alexdelprete** [comment]
> t should be quite clear.

no, it was not, if we're discussing the OP issue.

> and so I disabled the account it was to use.

and that shows an error (unknown you say). but still an error...and it will be investigated, but a total separate issue.

This last message is clear, the other was not. Hope you don't mind me asking just to be sure.

**Comment by alexdelprete** [comment]
No point continuing the discussion, it's not productive. :)

If you can, please open a new issue for the 401 error, thank you.
